### ISSUE TITLE
Default context is missing in templates when maintenance mode is on in Django 1.9

### ISSUE THREAD

**Issue by haidaraM** [fabiocaccamo/django-maintenance-mode#13]
I can't access some variables in context in templates when maintenance mode is on. For example the variables `request`and `maintenance_mode` are not available and I think some others variables also. I have to add them by myself by using `MAINTENANCE_MODE_TEMPLATE_CONTEXT`.

I think the problem is with this commit 4c2a6e5a6df62852c0cfcd3951e2013fc90b2713 when you added django 1.10 compatibility. I know there is a warning that says `The context_instance argument of render_to_string is deprecated...` but you can you use the `render` function as the documentation says https://docs.djangoproject.com/en/1.10/topics/http/shortcuts/#render-to-response.

I can make a pull request if you want.

**Comment by fabiocaccamo** [comment]
@haidaraM just released `0.4.4` where I use render instead of render_to_response if django version >= 1.8.
