### ISSUE TITLE
Add new setting to expire the user session

### ISSUE THREAD

**Issue by srus** [fabiocaccamo/django-maintenance-mode#139]
I think it would be useful to add a new setting to expire the user session. In combination with `MAINTENANCE_MODE_IGNORE_ANONYMOUS_USER = True`, you would let a logged user navigate the site as an anonymous user. It would be simple to implement, basically just adding the following under the `middleware.py` module:

```python
if settings.MAINTENANCE_MODE_EXPIRE_SESSION and request.user.is_authenticated():
    logout(request)
```

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/fabiocaccamo/django-maintenance-mode/issues/139">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/139/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/139/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@srus thank you for this suggestion, it seems very useful.

What do you think about naming this setting `MAINTENANCE_MODE_LOGOUT_AUTHENTICATED_USER`?

**Comment by srus** [comment]
Sure, sounds good to me, thanks.

**Comment by fabiocaccamo** [comment]
@srus by upgrading to `0.21.0` version you will be able to use the new `MAINTENANCE_MODE_LOGOUT_AUTHENTICATED_USER` setting, enjoy :)

**Comment by srus** [comment]
Great! Thank you very much!
