### ISSUE TITLE
MAINTENANCE_MODE_STATE_FILE_PATH could be configurable

### ISSUE THREAD

**Issue by ryselis** [fabiocaccamo/django-maintenance-mode#14]
currently MAINTENANCE_MODE_STATE_FILE_PATH points to directory of __file__ which on some setups is not writable and django-maintenance-mode is not usable on those setups. I think this option could be configurable via settings, just like the other settings of django-maintenance-mode.

**Comment by fabiocaccamo** [comment]
I will add it as soon as possible.

**Comment by fabiocaccamo** [comment]
`MAINTENANCE_MODE_STATE_FILE_PATH` is now configurable with `0.4.5` version.
