### ISSUE TITLE
Add Django Cache Backend

### ISSUE THREAD

**Issue by epicserve** [fabiocaccamo/django-maintenance-mode#153]
Is there a reason this library doesn't have a Django Cache Backend? I just wrote one, which seems generic enough to be added.

We need it because we have multiple web processes running behind a load balancer, and changing an environment variable that is used from the Django settings works. However, if we need to toggle the state, we have to reload the app, and under AWS ECS/Fargate, it takes about five minutes. This cache backend will allow us to toggle the state instantly instead of waiting five minutes for the app to reload.

Thoughts?

```
import logging

from django.core.cache import cache
from maintenance_mode.backends import AbstractStateBackend
from redis.exceptions import ConnectionError


logger = logging.getLogger(__name__)


class MaintenanceModeCacheBackend(AbstractStateBackend):
    def get_value(self):
        try:
            value = cache.get("maintenance_mode")
        except ConnectionError:
            logger.warning("Unable to connect to Django's cache backend. Maintenance mode is automatically set to on.")
            value = "1"
        self.from_bool_to_str_value(value)
        return value

    def set_value(self, value):
        # Using the following will cast the value to '0' when turning off maintenance mode, which causes it to not be
        # turned off. Leaving the line for reference as to why it was removed.
        # value = self.from_bool_to_str_value(value)
        try:
            cache.set("maintenance_mode", value, None)
        except ConnectionError:
            pass
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-maintenance-mode/issues/153">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/153/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/153/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@epicserve I think that's an useful thing to have, could you submit a PR includong tests?
