### ISSUE TITLE
1.10 MIDDLEWARE Compliant

### ISSUE THREAD

**Issue by fission6** [fabiocaccamo/django-maintenance-mode#16]
this should inherit 

from maintenance_mode.middleware import MaintenanceModeMiddleware

https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

**Comment by connexion2000** [comment]
Agreed, changing this line fixed error for me. Fabio could you also change it in repo?

**Comment by fabiocaccamo** [comment]
I just pushed the fix on master, could you check it? 
If it's ok I will release a new version n pypi.

**Comment by connexion2000** [comment]
Yes, now it works.

13.02.2017 10:26 AM "Fabio Caccamo" <notifications@github.com> napisał(a):
