### ISSUE TITLE
Support JSON content type

### ISSUE THREAD

**Issue by seiiedali** [fabiocaccamo/django-maintenance-mode#160]
In order to use this module in rest-framework and keep the backend and frontend work completely on JSON based API, it would be a good feature if I could return the http response with JSON content type as a response during maintenance mode with the predefined data. Thank you in advance for your considering this feature request.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-maintenance-mode/issues/160">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/160/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/160/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@seiiedali since `0.21.0` version it's possible to use `MAINTENANCE_MODE_RESPONSE_TYPE = "json"` setting, for passing the context data it's possible to use `MAINTENANCE_MODE_GET_CONTEXT` setting.

**Comment by seiiedali** [comment]
Thanks for the update🙏
