### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by flooreeda** [fabiocaccamo/django-maintenance-mode#17]
Are there plans to make this compatible with Python 3?

**Comment by fabiocaccamo** [comment]
@flooreeda it's not planned yet, feel free to send a PR.

**Comment by fraf1** [comment]
For info, I'm using this tool since September 2016 with Python 3 only (Python 3.5.1 and Django 1.9, Python 3.5.3 and Django 1.10). No problems found so far, apart from the command line usage with Django 1.10.5 for which I've done a pull request.

**Comment by fabiocaccamo** [comment]
@fraf1 thanks for your feedback. I will check your PR as soon as possible.

**Comment by fraf1** [comment]
Grazie!

Inviato da iPhone

**Comment by fabiocaccamo** [comment]
@flooreeda it is compatible with Python 3.

**Comment by flooreeda** [comment]
@fabiocaccamo & @fraf1, thanks! Works like a charm 👍
