### ISSUE TITLE
Inherit state file permissions from the directory where it is created.

### ISSUE THREAD

**Issue by fabiocaccamo** [fabiocaccamo/django-maintenance-mode#173]
#172

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-maintenance-mode/issues/173">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/173/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/173/pledge.svg">
</picture>
</a>

**Comment by PatrikSpurzem** [comment]
503 used from bots. Delet all newprofiles since 3 Month. Save old profiles from 503
