### ISSUE TITLE
django 1.9 comparable 

### ISSUE THREAD

**Issue by smbasha47** [fabiocaccamo/django-maintenance-mode#2]
Please update your URL's to django 1.9 comparable 

# -*- coding: utf-8 -*-

from django.conf.urls import  url
from . import views

urlpatterns = [
    url(r'^off/$', views.maintenance_mode_off, name='maintenance_mode_off'), 
    url(r'^on/$', views.maintenance_mode_on, name='maintenance_mode_on'), 
]

**Comment by fabiocaccamo** [comment]
Updated with 0.3.2 release, thanks.

**Comment by smbasha47** [comment]
still i am getting following deprecated warning

d:\python27\lib\site-packages\maintenance_mode\urls.py:10: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed i
  url(r'^on/$', views.maintenance_mode_on, name='maintenance_mode_on'),


i guess we should use below syntax for Django 1.10

urlpatterns = [
url(r'^off/$', views.maintenance_mode_off, name='maintenance_mode_off'), 
url(r'^on/$', views.maintenance_mode_on, name='maintenance_mode_on'), 
]

not sure how it behave for lower versions 

-Basha

**Comment by fabiocaccamo** [comment]
@smbasha47 I don't think that the new url patterns structure is backward-compatible. thanks for the warning report.
