### ISSUE TITLE
MAINTENANCE_MODE_GET_TEMPLATE_CONTEXT

### ISSUE THREAD

**Issue by Thulebona** [fabiocaccamo/django-maintenance-mode#22]
they is an error on the doc naming convection 
on the doc its says  `MAINTENANCE_MODE_GET_TEMPLATE_CONTEXT` but on the settings its getting `MAINTENANCE_MODE_TEMPLATE_CONTEXT`

`MAINTENANCE_MODE_GET_TEMPLATE_CONTEXT = getattr(settings, 'MAINTENANCE_MODE_TEMPLATE_CONTEXT', None)`

**Comment by fabiocaccamo** [comment]
Thanks for the report, I will fix it today.
