### ISSUE TITLE
Control maintenance mode via DB

### ISSUE THREAD

**Issue by jordmantheman** [fabiocaccamo/django-maintenance-mode#48]
(feature request)

Using a text file on the host doesn't work for django installations that distribute requests across multiple hosts. It seems like more of a detriment of the library to avoid using tables for this control than a benefit. Are the maintainers philosophically against this, or was it just a more expensive implementation than the sentinel file approach?

**Comment by fabiocaccamo** [comment]
@jordmantheman I know this limit, I thinks there could be 2 different ways to do this:

- Implement a small model/admin internally to the lib.

- Expose 2 new settings: `MAINTENANCE_MODE_STATE_GETTER` and `MAINTENANCE_MODE_STATE_SETTER` where it is possibile to define custom functions that implements the db read/write logic. This approach is the more flexible one.

**Comment by spapas** [comment]
One extra thing to consider is to allow the users to use redis (if it is present for cache) instead of the database; querying redis for a true/false value is faster than querying the database. 

The MAINTENANCE_MODE_STATE_GETTER you propose could probably be used for that (requiring the user to actually write the put/get code in the database) but I believe that it would be better to actually provide a buch of MAINTENANCE_MODE_STATE_GETTER for the user to use (probably two would be enough, one for the database and one for the redis backend similar to how django-constance backends work).

**Comment by jordmantheman** [comment]
Sorry for the delay!

Having configurable setters/getters is probably best. Agree w/ @spapas that a couple of baked in implementations could be useful. Perhaps an implementation using django-cache (assuming an in-memory store isn't used) would be a useful abstraction for someone using redis.

**Comment by fabiocaccamo** [comment]
Added pluggable backends support in `0.12.0` version, enjoy :).

**Comment by fabiocaccamo** [comment]
Just implement your custom backend extending `AbstractStateBackend`:

```python
import maintenance_mode.backends.AbstractStateBackend


class MaintenanceModeCustomBackend(AbstractStateBackend):

    def get_value(self):
		value = False
		# get the value here and return it
        return value

    def set_value(self, value):
        # store value
		pass
```

Then in `settipgs.py` set your custom backend class path:
```python
MAINTENANCE_MODE_STATE_BACKEND = 'myapp.backends.MaintenanceModeCustomBackend'
```

**Comment by adremides** [comment]
Can please provide an example how to implmenent db way to switch maintenance mode on/off with a custom backend?

**Comment by fabiocaccamo** [comment]
@adremides you just need to:
- create your own backend [extending the abstract backend](https://github.com/fabiocaccamo/django-maintenance-mode/blob/master/maintenance_mode/backends.py#L34)
- override the `get_value` and `set_value` methods (to get and set the state value as you need)
- set your backend as the default one using [settings](https://github.com/fabiocaccamo/django-maintenance-mode#settings) `settings.MAINTENANCE_MODE_STATE_BACKEND`

**Comment by adremides** [comment]
> * override the `get_value` and `set_value` methods (to get and set the state value as you need)

I have trouble figuring it out how to do that. How do I override those methods to write the value state to a field in the database?

**Comment by fabiocaccamo** [comment]
@adremides you can see existing backends to understand how to override a method. 
Concerning how to read/write a model field value the django documentation is very good: 
- https://docs.djangoproject.com/en/3.2/ref/models/instances/
- https://docs.djangoproject.com/en/3.2/ref/models/fields/#booleanfield
