### ISSUE TITLE
Maintenance mode cannot be turned off

### ISSUE THREAD

**Issue by bparker06** [fabiocaccamo/django-maintenance-mode#50]
If I comment out `MAINTENANCE_MODE = True`, I get this exception:

```
Exception Value: | [Errno 2] No such file or directory: '/territory/maintenance_mode_state.txt'
-- | --
/usr/local/lib/python3.5/dist-packages/maintenance_mode/io.py in write_file, line 26
```

Not sure why it's trying to write to some file in the root of the filesystem. If I add `MAINTENANCE_MODE_STATE_FILE_PATH = '/tmp/maintenance_mode_state.txt'`, this works as a temporary workaround.

**Comment by fabiocaccamo** [comment]
@bparker06 if you don't specify `MAINTENANCE_MODE_STATE_FILE_PATH`, [its default value](https://github.com/fabiocaccamo/django-maintenance-mode/blob/master/maintenance_mode/settings.py#L48) will be a `maintenance_mode_state.txt` file located in the same folder of your `settings.py` file.

Actually the code is well tested, could you write a test case to reproduce the error? Thanks

**Comment by bparker06** [comment]
Don't know anything about test cases, but I think there might be a chroot somewhere which would explain the app folder's absolute path starting with a `/`. So in this case I think it is just due to the app folder not being writable by the webserver user.

**Comment by fabiocaccamo** [comment]
I suggest you to read [this](https://docs.djangoproject.com/en/2.1/topics/testing/) :)
Yes, it could be related to permissions, but you should receive a `IOError`.
Could you list all the steps to follow to reproduce the error?
