### ISSUE TITLE
Bad default content type (charset)

### ISSUE THREAD

**Issue by OndrejIT** [fabiocaccamo/django-maintenance-mode#51]
Hello i found this problem:
![image](https://user-images.githubusercontent.com/11267809/46597225-8ef8fc00-cadf-11e8-9885-31c05294a05a.png)

problem is [here](https://github.com/fabiocaccamo/django-maintenance-mode/blob/3883d94c1f98b5f90565c22040556d27a6d97dcb/maintenance_mode/http.py#L53) content_type='text/html'
![image](https://user-images.githubusercontent.com/11267809/46597231-95877380-cadf-11e8-9c35-6026025a4933.png)

If i respect [DEFAULT_CHARSET](https://docs.djangoproject.com/en/2.1/ref/settings/#default-charset), problem is solved.
fixed in #49

**Comment by fabiocaccamo** [comment]
Released in `0.11.0` version with `python 3.7` and `django 2.1` support.
