### ISSUE TITLE
Configurable HTTP status code

### ISSUE THREAD

**Issue by andrewpwade** [fabiocaccamo/django-maintenance-mode#53]
I'm running an application on AWS Elastic Beanstalk which monitors the health of requests. HTTP 5xx is treated as an error by the monitoring processes and this doesn't seem configurable. 

One solution is to make maintenance mode return 200. I have a patch that adds a `MAINTENANCE_MODE_STATUS_CODE` setting with a default 503.

Would you accept a PR with this patch as it might be useful for others?

**Comment by fabiocaccamo** [comment]
Hi Andrew, 
sure!

**Comment by ngse** [comment]
Also a feature I'm looking for (same use-case: AWS EB deployment). Thanks for the patch @andrewpwade - looks like that will do what I need.

**Comment by fabiocaccamo** [comment]
Feature released with `0.13.0` version.
