### ISSUE TITLE
MAINTENANCE_MODE_IGNORE_IP_ADDRESSES does not work. 

### ISSUE THREAD

**Issue by Hoshitter1** [fabiocaccamo/django-maintenance-mode#55]
How does "else:
                client_ip_address = get_client_ip_address_func(request)_" (1st one)   work?

```
 if settings.MAINTENANCE_MODE_IGNORE_IP_ADDRESSES:
        if settings.MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS:
            try:
                get_client_ip_address_func = import_string(
                    settings.MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS)
            except ImportError:
                raise ImproperlyConfigured(
                    'settings.MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS '
                    'is not a valid function path.')
            else:
                client_ip_address = get_client_ip_address_func(request)_
        else:
            client_ip_address = get_client_ip_address(request)

        for ip_address in settings.MAINTENANCE_MODE_IGNORE_IP_ADDRESSES:

            ip_address_re = re.compile(ip_address)

            if ip_address_re.match(client_ip_address):
                return False
```

**Comment by fabiocaccamo** [comment]
There is no underscore: https://github.com/fabiocaccamo/django-maintenance-mode/blob/master/maintenance_mode/http.py#L174

**Comment by Hoshitter1** [comment]
Apart from this, Ive tried to use MAINTENANCE_MODE_IGNORE_IP_ADDRESSES in several ways but none of them worked even though other options worked properly. Just for the record I've put 
 this MAINTENANCE_MODE_IGNORE_IP_ADDRESSES = ("my_ip_here") by referring to http://www.myglobalip.com/ this website.  Is there any common errors with this function? Thank you!

**Comment by fabiocaccamo** [comment]
@Hoshitter1 what is the value of `MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS`?

This is default function to retrieve client ip address: 
https://github.com/fabiocaccamo/django-maintenance-mode/blob/master/maintenance_mode/utils.py

For a more advanced usage you should consider to use `django-ipware` as suggested in the README.
https://github.com/un33k/django-ipware

Could you write a view that outputs the ip address returned by both libs?
``` python
from maintenance_mode.utils import get_client_ip_address

client_ip = get_client_ip_address(request)
```
``` python
from ipware import get_client_ip

client_ip, is_routable = get_client_ip(request)
```

**Comment by Hoshitter1** [comment]
Thank you for your reply!

1. client_ip = get_client_ip_address(request)
client_ip  returns nothing

2. client_ip, is_routable = get_client_ip(request)
client_ip returns my ip address as also seen in 
http://www.myglobalip.com/
is_routable  returns True

**Comment by fabiocaccamo** [comment]
@Hoshitter1 could you try also with this function:
https://stackoverflow.com/questions/4581789/how-do-i-get-user-ip-address-in-django

**Comment by fabiocaccamo** [comment]
@Hoshitter1 as you can read, there is not a perfect solution.

I will suggest in the README to use `django-ipware`, I could do it by default but I prefere to keep thi lib dependency free.

Any suggestion is appreciated.

**Comment by Hoshitter1** [comment]
@fabiocaccamo I installed ipware and wrote MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS = 'ipware.ip.get_ip' right before MAINTENANCE_MODE_IGNORE_IP_ADDRESSES in settings.py as you suggested and it worked! Thank you for your support:)
