### ISSUE TITLE
Ignore urls

### ISSUE THREAD

**Issue by WrapTheCode** [fabiocaccamo/django-maintenance-mode#56]
Hi

I want be able to use in 503.html template a images from static directory.

I use in settings.py: 

`MAINTENANCE_MODE_IGNORE_URLS = (r'^/static/images/$',)`

but it doesnt work. I need help...

Thanks

**Comment by fabiocaccamo** [comment]
You don't need to add static and media urls to `MAINTENANCE_MODE_IGNORE_URLS`.

Your regexp ends with `$`, so it ignores only the path you specified and not everything under that path.

**Comment by WrapTheCode** [comment]
If i dont add MAINTENANCE_MODE_IGNORE_URLS to setting.py,  images from static dont load aswell...

**Comment by WrapTheCode** [comment]
I forgot to add that it is saleor aplication. 
Website is unable to reach even i have a superuser privileges.

**Comment by fabiocaccamo** [comment]
@WrapTheCode I can't reproduce the error, could you write a test case which fails please?

**Comment by WrapTheCode** [comment]
Just install https://github.com/mirumee/saleor
and https://github.com/fabiocaccamo/django-maintenance-mode.

**Comment by fabiocaccamo** [comment]
@WrapTheCode adding `MAINTENANCE_MODE_IGNORE_URLS = (r'^/static/images/',)` (without the trailing `$`) works fine?

**Comment by fabiocaccamo** [comment]
@WrapTheCode any update?

**Comment by rpombocastro** [comment]
@WrapTheCode try this MAINTENANCE_MODE_IGNORE_URLS = (r'/static/(?P<path>.*)',)

**Comment by rpombocastro** [comment]
MAINTENANCE_MODE_IGNORE_URLS = (r'/static/(?P<path>.*)',)
