### ISSUE TITLE
Update Installation Instructions

### ISSUE THREAD

**Issue by afurze** [fabiocaccamo/django-maintenance-mode#57]
Please update the installation instructions to include: "Add 'maintenance_mode.context_processors.maintenance_mode' to context_processors".  I didn't do this and it prevented the maintenance_mode template tag from working.

**Comment by fabiocaccamo** [comment]
@afurze https://github.com/fabiocaccamo/django-maintenance-mode#context-processors

**Comment by afurze** [comment]
Thanks for tolerating my idiocy :)

**Comment by fabiocaccamo** [comment]
No problem
