### ISSUE TITLE
'Settings' object has no attribute 'MAINTENANCE_MODE'

### ISSUE THREAD

**Issue by marksweb** [fabiocaccamo/django-maintenance-mode#59]
I've got a system in `MAINTENANCE_MODE` to perform a change to the database server. It's an RDS instance on AWS and I've changed it's type.

While the instance was being modified I was seeing the 503 response at first, but then that became `'Settings' object has no attribute 'MAINTENANCE_MODE'`.

Given the fact the app sets the default value to `None` django clearly wasn't running quite right while this happened, but it's a point in time that I have enabled `MAINTENANCE_MODE` and the system is undergoing changes so odd behaviour/side effects might be expected. Therefore could the app default to `MAINTENANCE_MODE = True` similar to;

```python
    def get_maintenance_mode():
        """
        Get maintenance_mode state from state file.
        """
        try:
            # If maintenance mode is defined in settings, it has priority.
            if settings.MAINTENANCE_MODE is not None:
                return settings.MAINTENANCE_MODE
        except AttributeError:
            return True

        backend = get_maintenance_mode_backend()
        return backend.get_value()
```

Full stacktrace;
```bash
AttributeError: 'Settings' object has no attribute 'MAINTENANCE_MODE'
  File "django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "newrelic/hooks/framework_django.py", line 220, in wrapper
    return wrapped(*args, **kwargs)
  File "maintenance_mode/middleware.py", line 19, in process_request
    if need_maintenance_response(request):
  File "maintenance_mode/http.py", line 93, in need_maintenance_response
    if not get_maintenance_mode():
  File "maintenance_mode/core.py", line 53, in get_maintenance_mode
    if settings.MAINTENANCE_MODE is not None:
  File "django/conf/__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
```

**Comment by fabiocaccamo** [comment]
@marksweb Have you run tests against your change? I don't think it will pass tests.
Could you send a PR with a failing test case to evidence your issue?

In any case, if the app will default to a value, it will default to `False` for backward compatibility.

**Comment by marksweb** [comment]
This isn't related to my branch, this is in `0.13.1` on the check for `if settings.MAINTENANCE_MODE` so also irrespective of any choice of backend instead of using settings.

**Comment by fabiocaccamo** [comment]
Could you send a PR with a failing test case please?

**Comment by niconoe** [comment]
Hello, I am encountering the same issue and believe the path by @marksweb would solve it!

To give some context, I believe this happens in my case because I manually configured my django logging (see https://docs.djangoproject.com/en/4.2/topics/logging/#disabling-logging-configuration), and as noted in Django's documentation:

> Note that the default configuration process only calls [LOGGING_CONFIG](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-LOGGING_CONFIG) once settings are fully-loaded. In contrast, manually configuring the logging in your settings file will load your logging config immediately. As such, your logging config must appear after any settings on which it depends.

Therefore, `maintenance_mode.logging.RequireNotMaintenanceMode503` get this error for all settings that are not explicitly set in my settings file (where I just accept the default values).

Tell me if I can help by providing more details!

**Comment by fabiocaccamo** [comment]
@niconoe sorry for the late answer. Are you able to recreate a failing test case to be able to fix the problem and avoid future regressions?
