### ISSUE TITLE
If there some custom processor is using django request, it returns an error.

### ISSUE THREAD

**Issue by jujumilk3** [fabiocaccamo/django-maintenance-mode#65]
My application is using django's request in context processor. but if i get into maintenance mode then error occurs.

The error follows 'NoneType' object has no attribute 'kwargs'.
it means i refer request's kwargs in context processor but if i turn on the maintenance mode, it can't find request. i solve this problem with 'if' sentence but it has to improve i think.

thanks for reading and this product. i'm using this very in a useful way.

**Comment by fabiocaccamo** [comment]
@jujumilk3 I think that this error could be related to the order or context processors in settings, could you paste here your context processors settings and your view?

**Comment by jujumilk3** [comment]
My python version is 3.7 and django is 2.2.6.
And view is almost a thousand lines so it's meaningless and this is production app so i can't upload, but i cant upload a part of it.

my context processor form was like
```python
def context_processor(request):
    context = {
    ...
    'selected_game': request.resolver_match.kwargs.get('game')
    ...
    }
```
It occurs an error.

>contexts['selected_game'] = request.resolver_match.kwargs.get('game')
AttributeError: 'NoneType' object has no attribute 'kwargs'

is the error content. i resolved this like

```python
def context_processor(request):
    context = {
    ...
    }
    if request.resolver_match:
        contexts['selected_game'] = request.resolver_match.kwargs.get('game')
```


And as u said, i was thought about context processors applying order but it doesn't worked.
This is my `settings.py`

```python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': []
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'maintenance_mode.context_processors.maintenance_mode',
                'myapp.context_processor.context_processor',
            ],
        },
    },
]
```

I tried to change that both things' ordering but nothing's changed.

**Comment by fabiocaccamo** [comment]
I understand, which `django-maintenance-mode` version are you using?

**Comment by jujumilk3** [comment]
It's django-maintenance-mode==0.14.0

**Comment by fabiocaccamo** [comment]
Could you send a PR with a test case for this?

**Comment by fabiocaccamo** [comment]
Could you try to move `myapp.context_processor.context_processor` before `maintenance_mode.context_processors.maintenance_mode` in  context processors?

**Comment by jujumilk3** [comment]
Same symptom again.
Can i ask what PR is?

**Comment by jujumilk3** [comment]
ah! that means pull request i got it.

**Comment by jujumilk3** [comment]
i made a repository for this issue.
https://github.com/jujumilk3/django-maintenance-mode-debug
check this out. sorry i don't know how to test with only django package. i just made simplest django app. every code need to check is in dir: maintenance_debug.

first. if maintenance mode is off, there's nothing problem. get in home and go to the test.html. there is message from context processor's request resolver.

but if turn on maintenance mode
```python
def context_processor(request):
    contexts = {
        'test1': 'test',
        'test2': request.resolver_match.kwargs.get('kwargs') # <- This code
    }
    return contexts

```
That code occurs an error.

**Comment by fabiocaccamo** [comment]
It's very simple, I will improve testing documentation.
Thank you for the info, I will test and fix it as soon as possible.

**Comment by fabiocaccamo** [comment]
I added testing step by step instructions to README: https://github.com/fabiocaccamo/django-maintenance-mode#testing

**Comment by jujumilk3** [comment]
omg thank you very much. because i couldn't find anywhere how to test separate django package.

**Comment by fabiocaccamo** [comment]
@jujumilk3 any update? Have you solved it?
