### ISSUE TITLE
Reason and Service Timeline

### ISSUE THREAD

**Issue by Butonix** [fabiocaccamo/django-maintenance-mode#67]
Hey.
Tell me, do you have such an opportunity to enable and disable the mode from the admin panel? And add a description + time to it

**Comment by fabiocaccamo** [comment]
@Butonix thank you for the suggestion. This topic has already been discussed here #48 
It is a nice feature, but I would prefer to keep it db/models free. Btw it is very easy to write a custom backend, check issue #48 for more details.
