### ISSUE TITLE
Redirect on /maintenance-mode/on

### ISSUE THREAD

**Issue by ramsondon** [fabiocaccamo/django-maintenance-mode#68]
The` /maintenance-mode/on` and` /maintenance-mode/off` urls should redirect back to the referring page instead of redirecting back to the main page in super admin.

**Comment by fabiocaccamo** [comment]
@ramsondon could you make me some example? 
We can't be sure that the referrer is a page of the current site.

**Comment by fabiocaccamo** [comment]
@ramsondon any feedback?

**Comment by fabiocaccamo** [comment]
I close this issue due to inactivity.
