### ISSUE TITLE
Disable emailing 503 errors to admins while maintenance mode is enabled

### ISSUE THREAD

**Issue by ChrisCrossCrash** [fabiocaccamo/django-maintenance-mode#72]
**Python version**
3.8

**Django version**
3.1.4

**Package version**
0.15.1

I think it would be nice to have a setting like this:
```
# Don't send 503 error emails to admins while maintenance mode is active
MAINTENANCE_MODE_DISABLE_503_EMAILS = True
```
By default, [Django sends emails to site admins for HTTP errors >= 500](https://docs.djangoproject.com/en/3.1/howto/error-reporting/#server-errors). It would be nice if this could be turned off while maintenance mode is on, since these errors would be expected at that time.

**Comment by fabiocaccamo** [comment]
@ChrisCrossCrash thank you for suggesting this. 
Have you any idea about how to achieve this in a transparent way?

**Comment by ChrisCrossCrash** [comment]
@fabiocaccamo I've looked into overriding the default logging settings just to avoid this happening in my app, but I haven't been able to figure it out yet. Also, I'm not sure how to make it a setting for Maintenance Mode as I've described above.

If it's not feasible to implement a setting like this, perhaps it would be helpful to users if there were a section in README.md describing how to modify `LOGGING` in settings.py so that they can avoid receiving 503 error emails while maintenance mode is active.

I'm just wrapping up on a big work project, but I'd love to give it a shot and contribute if you think it's a good idea. I just need a few days before I can focus on it more.

**Comment by fabiocaccamo** [comment]
@ChrisCrossCrash if you come to a solution using the logging system I will update the README section.

**Comment by ChrisCrossCrash** [comment]
I've found a solution that works for me, but how to implement it depends on how logging is set up for a particular project.

In my case, I was just using Django's default logging configuration.

Start by disabling the default logging configuration and enabling a custom configuration ([further details in Django docs][1]). Don't worry, we'll copy the defaults in the next step. In my project, the directory holding `settings.py` is named `drf_project`, so you'll need to substitute that with whatever it's called in your project.
```python
# drf_project/settings.py

import logging.config
from drf_project.custom_logging import CUSTOM_LOGGING

# Disable django default logging configuration.
LOGGING_CONFIG = None

# Load and enable a custom logging configuration for this project.
logging.config.dictConfig(CUSTOM_LOGGING)
```

Create a new file named `custom_logging.py` in the same directory as your `settings.py`. Then, paste in the following. You can also find the [DEFAULT_LOGGING value on GitHub][2] (make sure it matches your Django version):

```python
# drf_project/custom_logging.py

import logging
from django.conf import settings

# This is the `DEFAULT_LOGGING` value from `django/utils/log.py` (using Django 3.1.4).
CUSTOM_LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {message}',
            'style': '{',
        }
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'mail_admins'],
            'level': 'INFO',
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

class RequireNotMaintenanceMode503(logging.Filter):
    """Filters out 503 errors if maintenance mode is activated."""
    def filter(self, record):
        """Return False if maintenance mode is on and the given record has a status code of 503."""
        return not (settings.MAINTENANCE_MODE and getattr(record, 'status_code', None) == 503)

```

You'll notice that we now have a new filter class that filters out 503 errors while maintenance mode is enabled. However, it won't do anything until you make a new filter in your settings dictionary, and then add that filter to the `mail_admins` handler:

```python
CUSTOM_LOGGING = {
    'filters': {
        'require_not_maintenance_mode_503': {
            # TODO: replace `drf_project` with the directory holding custom_logging.py
            '()': 'drf_project.custom_logging.RequireNotMaintenanceMode503',
        },
        ...
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': [
                'require_debug_false',
                'require_not_maintenance_mode_503',
            ],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        ...
    },
    ...
}
```

The result is that you have Django's default logging configuration, except admins won't receive emails regarding 503 errors while maintenance mode is enabled.

As an added benefit, this setup makes changing Django logging settings much easier since all of your logging settings are in one place.

[1]: https://docs.djangoproject.com/en/3.0/topics/logging/#disabling-logging-configuration
[2]: https://github.com/django/django/blob/stable/3.1.x/django/utils/log.py

**Comment by fabiocaccamo** [comment]
@ChrisCrossCrash thank you for this solution.
Just a question: why you check both `settings.MAINTENANCE_MODE` and `status_code`?

I think that we could:
- Include the logging filter inside this library
- Document in the `README` the possibility to customize the logging

**Comment by ChrisCrossCrash** [comment]
Thanks @fabiocaccamo, I think those are good ideas. Adding the filter to the library would provide a solution while still giving users flexibility depending on their logging setup.

To answer your question, I only wanted to ignore 503 emails when maintenance mode is on. I still wanted 503 emails if maintenance mode was turned off. Also, I didn't want to ignore other (non-503) 'ERROR' level notifications when maintenance mode is on.

**Comment by fabiocaccamo** [comment]
@ChrisCrossCrash you can upgrade to `0.16.0` version and use the library [logger](https://github.com/fabiocaccamo/django-maintenance-mode#logging).

**Comment by ChrisCrossCrash** [comment]
@fabiocaccamo That's great! Thanks

**Comment by aliceni81** [comment]
settings.MAINTENANCE_MODE is static and cannot be changed when run "maintenance_mode <on|off>". So if I run the command or by other methods to change the maintenance mode, the error email still will be sent to admin. Will this filter be improved in the future?

**Comment by fabiocaccamo** [comment]
@aliceni81 thank you for reporting this, it should be enough to use `core.get_maintenance_mode()`, it automatically check the state from both, settings and backend.

**Comment by fabiocaccamo** [comment]
@aliceni81 you can upgrade to `0.16.1`.

**Comment by aliceni** [comment]
> @aliceni81 you can upgrade to `0.16.1`.

Thx!
