### ISSUE TITLE
Banner for all templates to warn users when maintenance will be

### ISSUE THREAD

**Issue by 9mido** [fabiocaccamo/django-maintenance-mode#73]
It would be awesome if there was a way to create something like this:
https://github-images.s3.amazonaws.com/enterprise/2.19/assets/images/enterprise/maintenance/maintenance-scheduled.png

to warn users ahead of time when maintenance mode will be scheduled. 

It would be nice to have a custom warning message and make the message css customizable like where it should be on your website like below the navbar or by the footer or somewhere else. I like at the bottom similar to a cookie banner but that is just me that the user could close/dismiss. Please use vanilla javascript and not jquery for this if it is needed.

Maybe make a page/setting to specify when the warning will be triggered and how long it will go for and automatically place the website into maintenance mode when the scheduled time happens.

**Comment by fabiocaccamo** [comment]
@9mido I close this issue because it is not in my intentions to add any kind of banner to this package, it is possible and very easy to check the maintenance mode state using the context processor and implement a custom banner if needed.
