### ISSUE TITLE
404 Not Found Error When SCRIPT_NAME Defined

### ISSUE THREAD

**Issue by tustunkok** [fabiocaccamo/django-maintenance-mode#74]
**Python version**
3.8

**Django version**
3.1

**Package version**
0.15.1

**Current behavior (bug description)**
When tried to enable the maintenance mode with a defined SCRIPT_NAME variable (under uWSGI), the app goes into the maintenance mode. However, returns 404 errors for every possible route including the maintenance-mode/off/ route. Thus, effectively prevents disabling the maintenance mode from the URL.

For example, assume that running under a `SCRIPT_NAME` `/pclink-test`. After enabling the maintenance mode, all routes start to give a 404 Not Found error with a message like `The current path, pclink-test/maintenance-mode/off/, didn't match any of these. `

**Expected behavior**
With a defined SCRIPT_NAME parameter in uWSGI, the application should gracefully turn off the maintenance mode when entered a URL like `http://example.com/<script-name>/maintenance-mode/off/` and shows the proper 503.html template instead of 404 Not Found errors.

**Comment by fabiocaccamo** [comment]
@tustunkok URLs are reversed using `django.urls.reverse`, if the reverse mechanism doesn't include the `SCRIPT_NAME` prefix it seems to be more a django bug.

Maybe the best solution would be to add `SCRIPT_NAME` prefix to your urls:
```python
urlpatterns = [
    # ...
    url(r'^{}/maintenance-mode/'.format(settings.SCRIPT_NAME), include('maintenance_mode.urls')),
    # ...
]
```

**Comment by tustunkok** [comment]
@fabiocaccamo Thank you for your quick response. I tested your suggestion. Now, the error string turned into `The current path, pclink-test/pclink-test/maintenance-mode/off/, didn't match any of these.`. So, I believe that django actually takes care of the subdirectory name.

Also, maybe it is good to mention that SCRIPT_NAME is not a settings variable. It is coming from NGINX server and defined as `uwsgi_param SCRIPT_NAME /pclink-test;` inside one of the virtual host configuration files.

**Comment by fabiocaccamo** [comment]
@tustunkok I understand, I'm sorry. If you come up with a solution feel free to submit a PR.

**Comment by tustunkok** [comment]
@fabiocaccamo OK, thank you for your time. I am investigating the problem.

**Comment by fabiocaccamo** [comment]
@tustunkok If you want try to find a solution I think you should put your hands [here](https://github.com/fabiocaccamo/django-maintenance-mode/blob/master/maintenance_mode/http.py#L100).

**Comment by tustunkok** [comment]
@fabiocaccamo I believe PR #75 should resolve the issue.

**Comment by fabiocaccamo** [comment]
@tustunkok please check the `FORCE_SCRIPT_NAME` django setting: https://docs.djangoproject.com/en/3.0/ref/settings/#force-script-name

**Comment by fabiocaccamo** [comment]
@tustunkok any update on this?

**Comment by tustunkok** [comment]
Hi, @fabiocaccamo . Yeah, actually I am using the solution that I suggested before in one of my applications. Unfortunately, I did not have time for providing any useful test case for the solution though.

**Comment by fabiocaccamo** [comment]
@tustunkok since this issue is stale and it seems more a problem of django than of this package, I close this issue.
