### ISSUE TITLE
Pass maintenance mode to all views

### ISSUE THREAD

**Issue by haidaraM** [fabiocaccamo/django-maintenance-mode#8]
I'm wondering if you plan to implement a way to know that if maintenance mode is on or off in all views. This can be implemented by using context processor https://docs.djangoproject.com/en/1.10/ref/templates/api/. 

It can be useful if we want to add some buttons to enable/disable the maintenance mode on web pages.

**Comment by fabiocaccamo** [comment]
Frankly that's not planned, feel free to send me a PR.

Anyway actually you can do it by using the core API https://github.com/fabiocaccamo/django-maintenance-mode#python

**Comment by haidaraM** [comment]
Yes you are right but you have to modify all your views if I understodd well. With a context processor it's just one function and maybe some others modifications.

I will send a PR and you can check...

**Comment by fabiocaccamo** [comment]
Fixed with 0.4.1 version
