### ISSUE TITLE
IGNORE_IP not working

### ISSUE THREAD

**Issue by Samoht1** [fabiocaccamo/django-maintenance-mode#80]
**Python version**
3.8.2

**Django version**
3.1.1

**Package version**
latest

**Current behavior (bug description)**
When I put my IP in the ignored variable, other PC's can still open the site without seeing the 503 template

**Expected behavior**
Only me accessing the site bypassing the 503 while others get the template

**Comment by fabiocaccamo** [comment]
@Samoht1 the setting `MAINTENANCE_MODE_IGNORE_IP_ADDRESSES` passes all the tests, do you set **maintenance mode** to `True` somehow?

Could you provide more informations, an example or a failing test, please? Otherwise I will close this issue.

**Comment by Samoht1** [comment]
yes, via command line. I can also actually maintenance_mode_state.txt change to 1

**Comment by fabiocaccamo** [comment]
@Samoht1 are you sure that other PC are not under the same router and the public IP is the same for all?

**Comment by Samoht1** [comment]
well sh*t.. they are... is it possible to use this feature with mac addresses?

**Comment by fabiocaccamo** [comment]
@Samoht1 frankly I don't know, this feature relies on [django-ipware](https://github.com/un33k/django-ipware), so you should check inside its documentation what is possible to do.

**Comment by Samoht1** [comment]
ah right, sorry I just assumed you made that feature too. I'll check it out, thanks!
