### ISSUE TITLE
CommandError: Unable to write state file at: maintenance_mode_state.txt

### ISSUE THREAD

**Issue by madatbay** [fabiocaccamo/django-maintenance-mode#81]
**Python version**
3.8.10

**Django version**
3.2.4

**Package version**
0.16.0

**Current behavior (bug description)**
In production turning maintenance mode via URL or `manage.py` returns error
```
CommandError: Unable to write state file at: maintenance_mode_state.txt
```

**Expected behavior**
Should toggle maintenance mode

**Comment by fabiocaccamo** [comment]
It is an IOError, please ensure that you have the permission to write the state file at that path.
