### ISSUE TITLE
Working fine on dev box but not functioning on test box with virtual directory

### ISSUE THREAD

**Issue by wjstarrsiii** [fabiocaccamo/django-maintenance-mode#82]
Hello, this package has been very useful for my use case.  It is working very well on my development box to redirect all but a whitelisted set of urls.  When I deploy to my testing environment, the mode_state.txt file is created, has proper permissions, etc, but absolutely no urls are redirected when it is on. 

The only difference between my dev box and testing are that on the dev box the root url is just a "server/".   On the test box, the application is in a virtual directory, so the url is "server/applicationname/".  I don't know if there is a setting in django to provide this virtual directory name that this package would use but my best guess is that this change in url is causing this package not to catch the redirects.  Any help would be much appreciated.

**Comment by fabiocaccamo** [comment]
I never used it, frankly I always use a subdomain in these cases. Thank you for the feedback!
