### ISSUE TITLE
MAINTENANCE_MODE_STATE_FILE_PATH setting bug

### ISSUE THREAD

**Issue by paduszyk** [fabiocaccamo/django-maintenance-mode#96]
**Python version**
3.10

**Django version**
4.1

**Package version**
0.16.3.

**Current behavior (bug description)**
When `MAINTENANCE_MODE_STATE_FILE_PATH` is defined using `pathlib.Path` (as suggested by the default Django settings file), e.g.:

```
MAINTENANCE_MODE_STATE_FILE_PATH = BASE_DIR.parent / "maintenance_mode_state.txt"
```

`AttributeError` is raised with message with message _'PosixPath' object has no attribute 'decode'_.

**Expected behavior**
It would be nice to define the path using `pathlib.Path` as well.

**Comment by fabiocaccamo** [comment]
@paduszyk nice catch, thank you!

**Comment by fabiocaccamo** [comment]
@paduszyk you can upgrade to `0.17.0` version.
